INSERT INTO student (id, name, age, grade_level, major)
VALUES 
  (1, 'John Doe', 20, 'Sophomore', 'Computer Science'),
  (2, 'Jane Smith', 19, 'Freshman', 'Mathematics'),
  (3, 'Bob Johnson', 21, 'Junior', 'History'),
  (4, 'Emily Brown', 20, 'Sophomore', 'English'),
  (5, 'Alex Rodriguez', 22, 'Senior', 'Biology'),
  (6, 'Grace Lee', 18, 'Freshman', 'Psychology'),
  (7, 'Michael Chang', 19, 'Sophomore', 'Chemistry'),
  (8, 'Karen Williams', 21, 'Junior', 'Economics'),
  (9, 'David Kim', 20, 'Sophomore', 'Political Science'),
  (10, 'Amy Chen', 22, 'Senior', 'Sociology'),
  (11, 'Ryan Park', 21, 'Junior', 'Art History'),
  (12, 'Jessica Lee', 19, 'Freshman', 'Engineering'),
  (13, 'Andrew Kim', 20, 'Sophomore', 'Physics'),
  (14, 'Samantha Wong', 21, 'Junior', 'Marketing'),
  (15, 'Tyler Smith', 22, 'Senior', 'Business'),
  (16, 'Erica Kim', 18, 'Freshman', 'Communications'),
  (17, 'Brandon Lee', 19, 'Sophomore', 'Computer Engineering'),
  (18, 'Jennifer Park', 21, 'Junior', 'International Relations'),
  (19, 'Kevin Chang', 20, 'Sophomore', 'Film Studies'),
  (20, 'Natalie Kim', 22, 'Senior', 'Accounting');