INSERT INTO student_record (student_id, course, assignment, score)
VALUES
  (1, 'SQL Basics', 'Midterm exam', 70),
  (1, 'SQL Basics', 'Final exam', 80),
  (2, 'SQL Basics', 'Midterm exam', 60),
  (2, 'SQL Basics', 'Final exam', 75),
  (3, 'SQL Basics', 'Midterm exam', 45),
  (3, 'SQL Basics', 'Final exam', 50),
  (4, 'SQL Basics', 'Midterm exam', 85),
  (4, 'SQL Basics', 'Final exam', 90),
  (5, 'SQL Basics', 'Midterm exam', 55),
  (5, 'SQL Basics', 'Final exam', 60),
  (6, 'SQL Basics', 'Midterm exam', 70),
  (6, 'SQL Basics', 'Final exam', 80),
  (7, 'SQL Basics', 'Midterm exam', 60),
  (7, 'SQL Basics', 'Final exam', 75),
  (8, 'SQL Basics', 'Midterm exam', 45),
  (8, 'SQL Basics', 'Final exam', 50),
  (9, 'SQL Basics', 'Midterm exam', 85),
  (9, 'SQL Basics', 'Final exam', 90),
  (10, 'SQL Basics', 'Midterm exam', 55),
  (10, 'SQL Basics', 'Final exam', 60),
  (11, 'JavaScript Basics', 'Midterm exam', 70),
  (11, 'JavaScript Basics', 'Final exam', 80),
  (12, 'JavaScript Basics', 'Midterm exam', 60),
  (12, 'JavaScript Basics', 'Final exam', 75),
  (13, 'JavaScript Basics', 'Midterm exam', 45);